[book]
authors = ["Matthias Schoenebeck"]
language = "en"
multilingual = false
src = "src"
title = "The ZEOS Book"

[output.katex]

[output.html]

[preprocessor.katex]
macros = "macros.txt"
renderers = ["html"]
